# Generated by Django 3.2.12 on 2022-03-23 14:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMeta',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
